export const pahQuerys = {
  getLastIdOrders: `select isnull(max(idPedido),10000) as lastId from pedidos where idCodigoPedido = 'NW'`,
  getAllClients: `select codigo,descripcion,condicionDePago,bonificacionGrupo,listaPrecios,listaOfertas,keyAccount,vendedor,habilitadoPedido,novedad,domicilio,cuit,telefono,codigoBonificacionGrupoCabecera from clientes `,
  getAllStocks: `select codigoProducto,stock from PAH_VW_stock `,
  getAllFamilies: `select codigo,descripcion, debaja as habilitado from familia `,
  getAllCombos: `select codigoFamilia as familia,codigoCombo combo,bonificacion,debaja from familiaComboBonificacion `,
  getAllDiscountGroup: `select codigoBG as codigo, descripcion, bonificacion, codigoCombo as comboBonificacion,habilitado FROM bonificacionGrupo `,
  getAllProducts: `SELECT 0 stockBase, codigo,descripcion,descripcionPack,cantidadPack,packFraccionable,cantMaximaVenta,familia,reemplazo,estado,observado,linkMH,unidadMedida,habilitado,novedad,precio FROM productos `,
  getAllPriceLists: `select codigoLista as codigo,moneda,oferta from listasDePrecios `,
  getAllDiscountCustomer: `select cliente,producto,bonificacion from bonificacionesClientes `,
  getAllPrices: `select producto,lista,precio,fechaDesde,fechaHasta from precio `,
  getAllLastPurchases: `select cliente,producto,cantidad,fecha from ultimascompras `,
  getAllSellers: `select mail,nombre,apellido,habilitado,codigoVendedor from vendedores `,
  getAllSellersCustomers: `select clientes.codigo as codigoCliente,vendedores.mail,vendedores.nombre,vendedores.apellido,vendedores.habilitado,vendedores.codigoVendedor FROM vendedores INNER JOIN clientes on clientes.vendedor = vendedores.codigoVendedor WHERE vendedores.novedad = 1 `,
  getAllDeliveryPoints: `select  codigo,cliente,direccion,transportista,habilitado from lugarEntrega `,
  getAllPaymentConditions: `select codigo,descripcion,activa,habilitado from condicionDePago `,
  getAllZones: `select codigo, descripcion, isnull(diasDeEntrega,'LMXJV') diasDeEntrega, habilitado from zona `,
  getAllTransporters: `SELECT codigo,razonSocial,zona,habilitado FROM transportistas `,
  getStatusOrders: `SELECT idPedido ,fechaEnvio fechaEntrega,case when estadoPedido='R' then 'recibido' when estadoPedido='P' then 'procesado' else 'enviado' end  estado,iva,iibbArba,iibbCaba,iibbOtras FROM pedidos `,
  getStatusItems: `SELECT idPedido ,idItem ,cantidadEnviada cantidad, estado, fechaSugerida as fechaEntrega, precio FROM items `,
  getPendingToDelivery: `SELECT idCodigoPedido codigoPedido,idItem,idPedido nroPedido,codigoProducto codigo,descripcionItem descripcion,unidadMedida unidad,descripcionPack pack,cantidadPendiente cantidad,solicitante,fechaEntrega fecha,estado,fechaAlta fechaPedido,codigoCliente,fechaPedido fechaPedidoNV FROM pendientesEntrega `,
};
